- name: Instalar eines
  hosts: all
  become: true
  gather_facts: true
  
  tasks:

  - name: Instalar dependencies
    ansible.builtin.apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      update_cache: yes
  
  - name: Afegir clau GPG docker
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg 

  - name: Afegir repositori docker
    ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu stable
      state: present
      update_cache: yes

  - name: Instalar docker
    ansible.builtin.apt:
      pkg:
        - docker-ce
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin
      state: latest
      update_cache: true

  - name: Afegir clau GPG kubernetes
    ansible.builtin.apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg 

  - name: Afegir repositori kubernetes
    ansible.builtin.apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      update_cache: yes
      
   - name: Instalar kubernetes
     ansible.builtin.apt:
       pkg:
         - kubeadm
         - kubectl
         - kubelet
       state: latest
       update_cache: true

  - name: Instalar minikube 
    ansible.builtin.shell:
